import { ArrowUpRight, Heart, MessageCircle, Radio, ShieldCheck, Sparkles, Users } from "lucide-react";
import Link from "next/link";
import { ThemeToggle } from "@/components/theme-toggle";
import { siteConfig } from "@/config/site";

const posts = [
  ["Anonymous #A72F", "OOPS", "Anyone know what happened in today’s OOPS class?", 12, 7],
  ["Anonymous #91BC", "Campus", "The library is unusually peaceful after 6pm. A small win during internals week.", 4, 18],
  ["Anonymous #28F1", "Hostel", "Can we get a proper notice before the water shutdown tomorrow?", 9, 11],
] as const;

export default function Home() {
  return <main className="min-h-screen overflow-hidden">
    <nav className="font-ui mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-5 sm:px-8"><Link className="flex items-center gap-2 text-xl font-bold tracking-tight" href="/"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[var(--teal)] text-sm text-[#061615]">W</span>{siteConfig.name}<span className="text-[var(--coral)]">/</span></Link><div className="hidden items-center gap-8 text-sm text-[var(--muted)] lg:flex"><a className="text-[var(--teal)]" href="#feed">Explore</a><a href="#rooms">Rooms</a><a href="#how">How it works</a></div><div className="flex items-center gap-3"><ThemeToggle/><Link href="/login" className="rounded-full bg-[var(--teal)] px-4 py-2 text-sm font-bold text-[#061615] shadow-lg shadow-teal-900/10">Sign in <ArrowUpRight className="ml-1 inline" size={15}/></Link></div></nav>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-20 pt-12 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:pb-28 lg:pt-24"><div className="absolute -right-40 top-0 h-96 w-96 rounded-full bg-[var(--teal)]/10 blur-3xl"/><div className="relative"><p className="eyebrow mb-6 flex items-center gap-2"><Sparkles size={15}/> A quieter campus signal</p><h1 className="max-w-3xl text-5xl leading-[.95] tracking-[-.045em] sm:text-7xl lg:text-8xl">Say what you mean.<br/><span className="text-[var(--teal)]">Stay anonymous.</span></h1><p className="font-ui mt-8 max-w-xl text-base leading-8 text-[var(--muted)] sm:text-lg">A private signal layer for {siteConfig.collegeName}. Ask questions, find your people, and make campus feel a little more connected.</p><div className="font-ui mt-9 flex flex-wrap items-center gap-3"><Link href="/login" className="rounded-full bg-[var(--teal)] px-6 py-3 text-sm font-bold text-[#061615] shadow-xl shadow-teal-900/15">Enter {siteConfig.name} <ArrowUpRight className="ml-2 inline" size={16}/></Link><a href="#feed" className="rounded-full border border-[var(--line)] bg-[var(--panel)] px-6 py-3 text-sm font-bold">Scan the feed</a></div><div className="font-ui mt-10 flex items-center gap-6 text-xs text-[var(--muted)]"><span><span className="mr-2 text-[var(--teal)]">●</span>Private by default</span><span className="flex items-center gap-2"><ShieldCheck size={14}/>Platform accountable</span></div></div><div className="relative lg:pl-8"><div className="absolute -inset-8 rounded-full bg-[var(--cyan)]/10 blur-3xl"/><div className="glass-panel relative rotate-1 rounded-[26px] p-4 sm:p-5"><div className="font-ui flex items-center justify-between border-b border-[var(--line)] pb-4 text-[10px] font-bold uppercase tracking-[.18em] text-[var(--muted)]"><span className="flex items-center gap-2"><Radio size={14} className="text-[var(--teal)]"/> Live campus feed</span><span className="text-[var(--teal)]">03 active</span></div><div className="space-y-3 py-4">{posts.slice(0, 2).map((post, index) => <article key={post[0]} className="rounded-2xl border border-[var(--line)] bg-[var(--panel)] p-4"><div className="font-ui mb-3 flex items-center justify-between text-xs"><span className="font-bold">{post[0]}</span><span className="text-[var(--muted)]">0{index + 8}m</span></div><p className="text-lg leading-6">{post[2]}</p><div className="font-ui mt-4 flex items-center gap-4 text-xs text-[var(--muted)]"><span className="font-bold text-[var(--teal)]">#{post[1]}</span><span><Heart size={13} className="mr-1 inline"/>{post[4]}</span><span><MessageCircle size={13} className="mr-1 inline"/>{post[3]}</span></div></article>)}</div><div className="font-ui flex items-center justify-between border-t border-[var(--line)] pt-4 text-xs text-[var(--muted)]"><span>Anonymous conversations</span><span className="text-[var(--teal)]">Encrypted session</span></div></div></div></section>
    <section id="feed" className="mx-auto max-w-7xl px-5 pb-24 sm:px-8"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">The student signal</p><h2 className="mt-3 text-4xl tracking-[-.03em] sm:text-5xl">What’s on your mind?</h2></div><Link className="font-ui text-sm font-bold text-[var(--teal)]" href="/login">See all conversations <ArrowUpRight className="ml-1 inline" size={15}/></Link></div><div className="grid gap-4 md:grid-cols-3">{posts.map((post, index) => <article key={post[0]} className="glass-panel group flex min-h-72 flex-col rounded-2xl p-5 transition duration-300 hover:-translate-y-1 hover:border-[var(--teal)]"><div className="font-ui flex justify-between text-xs"><span className="font-bold">{post[0]}</span><span className="text-[var(--muted)]">{index + 1}h ago</span></div><p className="mt-7 flex-1 text-xl leading-7">{post[2]}</p><div className="font-ui mt-6 flex items-center justify-between border-t border-[var(--line)] pt-4 text-xs"><span className="font-bold text-[var(--teal)]">#{post[1]}</span><span className="flex gap-4 text-[var(--muted)]"><span><MessageCircle size={14} className="mr-1 inline"/>{post[3]}</span><span><Heart size={14} className="mr-1 inline"/>{post[4]}</span></span></div></article>)}</div></section>
    <section id="how" className="mx-auto grid max-w-7xl gap-10 px-5 pb-24 sm:px-8 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="eyebrow">Signal, without the noise</p><h2 className="mt-3 text-4xl tracking-[-.03em] sm:text-5xl">Built for honest campus conversations.</h2></div><div className="grid gap-3 sm:grid-cols-3"><div className="glass-panel rounded-2xl p-5"><span className="font-ui text-xs font-bold text-[var(--teal)]">01 / AUTH</span><Users className="my-8 text-[var(--teal)]" size={25}/><p className="font-ui text-sm leading-6 text-[var(--muted)]">Verify with your college email. Your identity stays private from students.</p></div><div className="glass-panel rounded-2xl p-5"><span className="font-ui text-xs font-bold text-[var(--teal)]">02 / VOICE</span><Sparkles className="my-8 text-[var(--teal)]" size={25}/><p className="font-ui text-sm leading-6 text-[var(--muted)]">Post into focused rooms with an anonymous label that says nothing about you.</p></div><div className="glass-panel rounded-2xl p-5"><span className="font-ui text-xs font-bold text-[var(--teal)]">03 / CARE</span><ShieldCheck className="my-8 text-[var(--teal)]" size={25}/><p className="font-ui text-sm leading-6 text-[var(--muted)]">Moderation keeps the platform accountable without exposing students publicly.</p></div></div></section>
    <section id="rooms" className="font-ui mx-5 mb-10 flex max-w-7xl flex-col justify-between gap-6 rounded-3xl bg-[var(--teal)] px-7 py-9 text-[#061615] sm:mx-8 sm:px-10 lg:mx-auto lg:flex-row lg:items-center"><div><p className="text-xs font-bold uppercase tracking-[.18em] opacity-70">Built for {siteConfig.collegeName}</p><h2 className="mt-2 text-3xl font-bold tracking-tight">A room for every campus thread.</h2></div><div className="flex flex-wrap gap-2 text-sm font-bold"><span className="rounded-full bg-black/10 px-3 py-2">General</span><span className="rounded-full bg-black/10 px-3 py-2">Subjects</span><span className="rounded-full bg-black/10 px-3 py-2">Hostel</span></div></section>
    <footer className="font-ui mx-auto flex max-w-7xl flex-col gap-3 border-t border-[var(--line)] px-5 py-8 text-xs text-[var(--muted)] sm:flex-row sm:items-center sm:justify-between sm:px-8"><span>{siteConfig.name} / {siteConfig.collegeName}</span><span className="flex items-center gap-2"><ShieldCheck size={14}/> Anonymous to students. Accountable to the platform.</span></footer>
  </main>;
}
